config/routes.rb
RomaMoneyRails::Application.routes.draw do
   #get "transactions/new"
  # get "transactions/create"
  # get "transactions/edit"
  # get "transactions/update"
  # get "transactions/destroy"
  
  # get "accounts/new"
  # get "accounts/destroy"
  #get "users/new"
  root :to => "home#index"


  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

 # root  'home#index'
  match '/',        to: 'home#index',    via: 'get'
  match '/home',    to: 'home#index',    via: 'get'
  match '/help',    to: 'home#help',    via: 'get'
#  match '/about',   to: 'static_pages#about',   via: 'get'
#  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/createAccount',  to: 'accounts#new',            via: 'get'
  match '/createTransaction',  to: 'transactions#new',            via: 'get'

  match '/stats',  to: 'transactions#stats',            via: 'get'

  match '/invite_user_to_account',  to: 'accounts#invite_user_to_account',            via: 'post'


  resources :accounts do
    member do
        post :invite_user_to_account
    end
  end


  resources :transactions do
    member do
      get :stats
    end
  end
    
  resources :users do
    member do
      get :change_to_this, :change_account, :change_account_ajax   #define following_user_path, followers_user_path
    end
  end

    #member do
    #  get :xxx, :yyy   #define xxx_user_path, yyy_user_path
  #  end
  
 resources :sessions, only: [:new, :create, :destroy]


end

app/views/shared/_account_balance.html.erb
<div id="account_balance">
	<p class="value-<%=current_user.current_account.how_is_balance%>">
		<b>Balance:</b> 
		<strong>
			$ <%= current_user.current_account.current_balance %>
		</strong>
	</p>
</div>

app/views/shared/_account_list.html.erb
<span id="account_list" class="dropdown center">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <%= current_user.current_account.name %> <b class="caret"></b>
    </a>
	<ul class="dropdown-menu">  
		<% current_user.accounts.each do |account| %>
			<% if account.name != current_user.current_account.name %>
				<li> <%= link_to account.name, change_account_ajax_user_path(account), remote: true %>
		        </li>

			<%end%>
		<% end %>
	 </ul>
</span>

app/views/shared/_balance.html.erb
<p id="account_balance" class="value-<%=current_user.current_account.how_is_balance%>">
	<b>Balance:</b> 
	<strong>
		$ <%= current_user.current_account.balance %>
	</strong>
</p>

app/views/shared/_date_account.html.erb
<div id="date_account">
	 <p>
	     Created <%= time_ago_in_words(current_user.current_account.created_at) %> ago.
	 </p>
	 <p>Created at <%= current_user.current_account.created_at.strftime("%d/%b/%Y") %>
	 </p>
</div>

app/views/shared/_error_messages.html.erb
<div id="error_explanation">
    <% if object.errors.any? %>
        <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
      	<% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
      </ul>
  <% end %>
</div>

app/views/shared/_user_account_list.html.erb
<span id="user_account_list" class="dropdown center">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <%= current_user.name %> <b class="caret"></b>
    </a>
	<ul class="dropdown-menu">
		<% current_user.current_account.users.each do |user| %>
			<% if user.id != current_user.id %>
				<li><%= user.name %> </li>
			<%end%>
		<% end %>
	 </ul>
</span>

app/views/shared/_user_summary.html.erb
  <section>
    <p><%= gravatar_for current_user, {size:80} %>
    <h4>
      <p><%= current_user.name %>
    </h4>
    <p>Joined on Jun 08, 2013
  </section>
  
<% if current_user.current_account.present? %>
	<div class="row">
		<div class="span4 grey-box" >
			<b>Current Account:</b><%= render 'shared/account_list' %><br>
			<b >Users:</b><%= render 'shared/user_account_list' %>
			<%= render 'shared/account_balance' %>
	    	<%= render 'shared/date_account' %>
   	    	<div class="center">
		        <%= link_to  "Add Transaction new page", new_transaction_path, class: "btn btn-small btn-primary" %>
	    	</div>
	    <% if !current_user.current_account.transactions.empty? %>
			<div class="center" style="padding:5px;margin:5px">
				<button onclick="return showDialogAddTransaction()" class="btn btn-small btn-primary" >Add Transaction Dialog</button>
			</div>
		<% end %>
	</div>
	<div class="span4 center grey-box">    	
		<div style="margin-bottom:10px">
	        <%= link_to  "Manage Accounts", accounts_path, class: "btn btn-medium btn-primary" %>
		</div>		
		<div >
	        <%= link_to  "New Account", createAccount_path, class: "btn btn-medium btn-primary" %>
		</div>
	</div>
	<% if !current_user.current_account.transactions.empty? %>
	<% if false%>
		<div class="span4 grey-box " >
		    <%= form_for(new_transaction, remote:true) do |f| %>
			    <%= render 'transactions/fields_transaction', f: f %>
			    <center>
	   				<%= f.submit "Add Transaction", class: "btn btn-large btn-primary" %>
	   			</center>
	   		<% end %>
		</div>
	<%end%>
	<% end %>
	<div id="addTransaction" title="Add a transaction" style="display:none">
		<div class="span4 transaction-box">
		    <%= form_for(new_transaction, remote:true) do |f| %>
			    <%= render 'transactions/fields_transaction', f: f %>
			    <center>
      				<%= f.submit "Add Transaction", class: "btn btn-large btn-primary" %>
      			</center>
    		<% end %>
		</div>
	</div>    
<%end%>	

  