config/routes.rb
RomaMoneyRails::Application.routes.draw do
   #get "transactions/new"
  # get "transactions/create"
  # get "transactions/edit"
  # get "transactions/update"
  # get "transactions/destroy"
  
  # get "accounts/new"
  # get "accounts/destroy"
  #get "users/new"
  root :to => "home#index"


  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

 # root  'home#index'
  match '/',        to: 'home#index',    via: 'get'
  match '/home',    to: 'home#index',    via: 'get'
  match '/help',    to: 'home#help',    via: 'get'
#  match '/about',   to: 'static_pages#about',   via: 'get'
#  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/createAccount',  to: 'accounts#new',            via: 'get'
  match '/createTransaction',  to: 'transactions#new',            via: 'get'

  match '/stats',  to: 'transactions#stats',            via: 'get'

  match '/invite_user_to_account',  to: 'accounts#invite_user_to_account',            via: 'post'


  resources :accounts do
    member do
        post :invite_user_to_account
    end
  end


  resources :transactions do
    member do
      get :stats
    end
  end
    
  resources :users do
    member do
      get :change_to_this, :change_account, :change_account_ajax   #define following_user_path, followers_user_path
    end
  end

    #member do
    #  get :xxx, :yyy   #define xxx_user_path, yyy_user_path
  #  end
  
 resources :sessions, only: [:new, :create, :destroy]


end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :signed_in_user

  include ApplicationHelper
  respond_to :html, :js

  def new
    @transaction = new_transaction
  end

  def index
    if current_user != nil && current_user.current_account != nil
      @transactions = current_user.current_account.transactions.paginate(page: params[:page])
    end
  end


  def stats
    flash[:error] = nil
    flash[:success] = nil

    @transactions = Transaction.where("account_id = ?", current_user.current_account)

    @result = Transaction.unscoped.select("category_id, sum(value) as sum_value").group("category_id")

    data_income = []
    data_income_percentage = []
    data_expense = []
    data_expense_percentage = []

    sum_expense = 0
    sum_income = 0

    @result.each do |r|
      cat = Category.find(r.category_id)
      if(cat.group_category_id == 1)
        sum_income += r.sum_value;
      else
        sum_expense += r.sum_value;
      end
    end

    @result.each do |r|
      cat = Category.find(r.category_id)
      if(cat.group_category_id == 1)
        percentage = (100*r.sum_value/sum_income).to_i
        data_income_percentage << [cat.name, percentage]
        data_income <<  [cat.name, r.sum_value]
      else
        percentage = (100*r.sum_value/sum_expense).to_i
        data_expense_percentage << [cat.name, percentage]
        data_expense <<  [cat.name, r.sum_value]
      end
    end

    @chart_income = LazyHighCharts::HighChart.new('pie') do |f|
        f.chart({:defaultSeriesType=>"pie" , :margin=> [50, 0, 0, 0]} )
        series = {
                 :type=> 'pie',
                 :name=> 'Incomes',
                 :data=> data_income
        }
        f.series(series)
        f.options[:title][:text] = "Incomes"
        f.legend(:layout=> 'vertical',:style=> {:left=> 'auto', :bottom=> 'auto',:right=> '50px',:top=> '100px'}) 
        f.plot_options(:pie=>{
          :allowPointSelect=>true, 
          :cursor=>"pointer" , 
          :dataLabels=>{
            :enabled=>true,
            :color=>"black",
            :style=>{
              :font=>"13px Trebuchet MS, Verdana, sans-serif"
            }
          }
        })
    end
    @chart_income_percentage = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({:defaultSeriesType=>"pie" , :margin=> [50, 0, 0, 0]} )
      series = {
               :type=> 'pie',
               :name=> 'Incomes Percentage',
               :data=> data_income_percentage
      }
      f.series(series)
      f.options[:title][:text] = "Incomes Percentage"
      f.legend(:layout=> 'vertical',:style=> {:left=> 'auto', :bottom=> 'auto',:right=> '50px',:top=> '100px'}) 
      f.plot_options(:pie=>{
        :allowPointSelect=>true, 
        :cursor=>"pointer" , 
        :dataLabels=>{
          :enabled=>true,
          :color=>"black",
          :style=>{
            :font=>"13px Trebuchet MS, Verdana, sans-serif"
          }
        }
      })
    end
    @chart_expense = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({:defaultSeriesType=>"pie" , :margin=> [50, 0, 0, 0]} )
      series = {
               :type=> 'pie',
               :name=> 'Expenses',
               :data=> data_expense
      }
      f.series(series)
      f.options[:title][:text] = "Expenses"
      f.legend(:layout=> 'vertical',:style=> {:left=> 'auto', :bottom=> 'auto',:right=> '50px',:top=> '100px'}) 
      f.plot_options(:pie=>{
        :allowPointSelect=>true, 
        :cursor=>"pointer" , 
        :dataLabels=>{
          :enabled=>true,
          :color=>"black",
          :style=>{
            :font=>"13px Trebuchet MS, Verdana, sans-serif"
          }
        }
      })
    end
    @chart_expense_percentage = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({:defaultSeriesType=>"pie" , :margin=> [50, 0, 0, 0]} )
      series = {
               :type=> 'pie',
               :name=> 'Expenses percentage',
               :data=> data_expense_percentage
      }
      f.series(series)
      f.options[:title][:text] = "Expenses percentage"
      f.legend(:layout=> 'vertical',:style=> {:left=> 'auto', :bottom=> 'auto',:right=> '50px',:top=> '100px'}) 
      f.plot_options(:pie=>{
        :allowPointSelect=>true, 
        :cursor=>"pointer" , 
        :dataLabels=>{
          :enabled=>true,
          :color=>"black",
          :style=>{
            :font=>"13px Trebuchet MS, Verdana, sans-serif"
          }
        }
      })
    end
    render 'stats'
  end


  def createStandard
    @transaction = Transaction.new(transaction_params)
    @transaction.account = current_user.current_account

    categoryGroup_radio = params[:categoryGroup_radio]
    category = 0
    if categoryGroup_radio == nil
      flash[:error] = "Please, select a group of category."
      render 'new'
      return
    end
    if categoryGroup_radio == "income"
      category = params[:category_income]
    else categoryGroup_radio == "expense"
      category = params[:category_expense]
    end
  
    category = Category.find(category)
    @transaction.category = category

    if @transaction.save
      flash[:success] = "Transaction #{@transaction.name} created!"
      flash[:success] = "params=#{params}"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def create
    flash[:error] = nil
    flash[:success] = nil
    @transaction = Transaction.new(transaction_params)
    @transaction.account = current_user.current_account

    categoryGroup_radio = params[:categoryGroup_radio]
    category = 0
    if categoryGroup_radio == nil
      flash[:error] = "Please, select a group of category."
    else
      if categoryGroup_radio == "income"
        category = params[:category_income]
      else categoryGroup_radio == "expense"
        category = params[:category_expense]
      end

      category = Category.find(category)

      @transaction.category = category

      if @transaction.save
        flash[:success] = "Transaction #{@transaction.name} created!"
      else
        flash[:error] = "Transaction #{@transaction.name} could not be created!"
      end
    end
    @transactions = current_user.current_account.transactions.paginate(page: params[:page])
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js 
       #     render :partial => "transaction_history", :object => @transactions
    end

  end


  def edit
    @transaction = Transaction.find(params[:id])
    
    if @transaction.category.group_category_id == 1
      @current_category_income = @transaction.category.id
    else
      @current_category_expense = @transaction.category.id
    end
  end

  def update
    @transaction = Transaction.find(params[:id])

    categoryGroup_radio = params[:categoryGroup_radio]
    category = 0
    if categoryGroup_radio == nil
      flash[:error] = "Please, select a group of category."
      render 'edit'
      return
    end

    if categoryGroup_radio == "income"
      category = params[:category_income]
    else
      category = params[:category_expense]
    end

    category = Category.find(category)
    if category == nil
        flash[:error] = "Category not set!"
        render 'edit'
        return
    end
    @transaction.category = category

    if(@transaction.invalid?)
      @transaction.errors.full_messages.each do |e|
        flash[e] = e
      end
      render 'edit'
      return

    end

    
    if @transaction.update_attributes(transaction_params)
      # Handle a successful update.
      flash[:success] = "Transaction updated."
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroyStandard
      transaction = Transaction.find(params[:id])

      transaction.destroy
      flash[:success] = "Transaction deleted."
      redirect_to root_url
  end

  def destroy
      transaction = Transaction.find(params[:id])
      transaction.destroy
      @transactions = current_user.current_account.transactions.paginate(page: params[:page])

      # if @transactions.empty?
      #   redirect_to root_url
      # else
        flash[:success] = "Transaction deleted."
        respond_to do |format|
          format.html { redirect_to root_url }
          format.js
        end
      # end
  end

  private
    def transaction_params
      params.require(:transaction).permit(:name, :description, 
                                              :value, :date)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper

end

app/views/transactions/_fields_transaction.html.erb
 <%= render 'shared/error_messages', object: f.object %>

<%= f.text_field :name , :placeholder=>"Name"%>

<%= f.text_area :description, rows:3, :placeholder=>"Description"%>

<%= f.text_field :value, :placeholder=>"Value"%>

<div >
	Group:
	<input id="categoryGroup_radio_income" type="radio" name="categoryGroup_radio" onchange="handleChange(this);" value="income"
	<% if @current_category_income.present? %>
		checked
	<% end %>
	>Income
	<input id="categoryGroup_radio_expense" type="radio" name="categoryGroup_radio" onchange="handleChange(this);" value="expense"
	<% if @current_category_expense.present? %>
		checked
	<% end %>
	>Expense
	<p>
</div>

<div id="select_income" class="class_select_income"
	<% if !@current_category_income.present? %>
		style="display:none"
	<% end %>
 >
	Income
	<%= select_tag(:category_income, options_from_collection_for_select(categories_by_group(1), :id, :name, :prompt => true, :selected => @current_category_income)) %>
</div>
<div id="select_expense" class="class_select_expense" 
	<% if !@current_category_expense.present? %>
		style="display:none"
	<% end %>

	Expense
	<%= select_tag(:category_expense, options_from_collection_for_select(categories_by_group(2), :id, :name, :prompt => true, :selected => @current_category_expense)) %>
</div>

<%= f.label :date %>
<%= f.text_field(:date, :class=>"hasdatepicker", :width=>"30px", :id=>"datepicker") %>


<script>
  $(function() {
    $( "#datepicker" ).datepicker( { dateFormat: 'dd/mm/yy' } );
    $( "#datepicker" ).datepicker();
  });
  </script>

app/views/transactions/_transaction.html.erb
<div class="transaction-box">
	<p><b>Transaction Name: </b><%=transaction.name%></p>

	<p><b>Description:</b><%=transaction.description%>
	</p>
	<p class="value-<%=transaction.how_is_value%>">
		<b>Value:</b> $ <%= transaction.value %>
	</p>
	<p><b>Date: </b><%= transaction.date.strftime("%d/%b/%Y") %>

	<p><b>Account: </b><%= transaction.account.name %>
	<p><b>Category: </b><%= transaction.category.name %>
	<p>
	<%= link_to "Change", edit_transaction_path(transaction) %>
    | <%= link_to "delete", transaction, method: :delete, remote: true,
                                  data: { confirm: "You sure?" } %>

</div>

app/views/transactions/_transaction_history.html.erb
 <div id="history_of_transactions" class="span8" >
	<%= will_paginate %>

	<div class="transactions">
	  <% @transactions.each do |transaction| %>
	    <%= render transaction %>  <!-- Call view/accounts/_transaction.html.erb  -->
	  <% end %>
	</div>  

	<%= will_paginate %>   </div>
</div>	

app/views/transactions/_verify_transactions.html.erb
<div id="verify_transactions">
		<% if @transactions.present? && @transactions.size > 0%>
		<div class="span8 center">    
			<h3>All Transactions</h3>
		</div>
		<%= render 'transactions/transaction_history' %>  
	<% else %>
		<div class="span8 center grey-box" style="padding:10px">    	
			<div style="margin-bottom:10px">
		        <%= link_to  "Manage Accounts", accounts_path, class: "btn btn-medium btn-primary" %>
			</div>		
			<div >
		        <%= link_to  "New Account", createAccount_path, class: "btn btn-medium btn-primary" %>
			</div>
		</div>
		<% if current_user.current_account.present? %>
			<div class="span8 center"><h3> You don't have any transaction</h3></div>
			<div class="span6 offset1 center grey-box">
			    <%= form_for(new_transaction, controller: 'transactions', action:'createStandard') do |f| %>

			      <%= render 'transactions/fields_transaction', f: f %>
			      <%= f.submit "Create a new transaction", class: "btn btn-large btn-primary" %>
			    <% end %>
			</div>
		<% end %>

	<% end %>
</div>

app/views/transactions/create.js.erb
$("#history_of_transactions").html("<%= escape_javascript(render('transactions/transaction_history')) %>")
$("#account_balance").html('<%= current_user.current_account.balance %>')

app/views/transactions/destroy.js.erb
$("#messages").html("")
$("#messages").html("<%= escape_javascript(render('layouts/messages')) %>")
$("#history_of_transactions").html("<%= escape_javascript(render('transactions/transaction_history')) %>")
//$("#account_balance").html('<%= current_user.current_account.balance %>')
$("#account_balance").html("<%= escape_javascript(render('shared/account_balance')) %>")

app/views/transactions/edit.html.erb
<% provide(:title, "Edit and Transaction") %>
<div class="row">
  <aside class="span4">
      
  </aside>
  <div class="span6 transaction-box">
  	<h3>Update an Transaction</h3>
    <%= form_for(@transaction) do |f| %>
      <%= render 'fields_transaction', f: f %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/transactions/index.html.erb
<% provide(:title, 'All Transactions') %>
<div class="row">
  <aside class="span4">
      <%= render 'shared/user_summary' %>  
  </aside>
  <div class="span8">
  	<% if current_user.current_account.present? || current_user.accounts_size > 0 %>
  		<%= render 'transactions/verify_transactions' %>  
	<% else %>
		<div class="span8 center grey-box" style="padding:10px">    
			<div >
		        <%= link_to  "New Account", createAccount_path, class: "btn btn-medium btn-primary" %>
			</div>
		</div>
	<% end %>

  </div>	
</div>	  

app/views/transactions/new.html.erb
<% provide(:title, 'Create Transaction') %>

<div class="row">
  <aside class="span4">
      
  </aside>
  <div class="span6 transaction-box ">
  	<h1>Create a new Transaction</h1>

    <%= form_for(@transaction, controller: 'transactions', action:'createStandard') do |f| %>

      <%= render 'fields_transaction', f: f %>
      <div class="center">
      	<%= f.submit "Create a new transaction", class: "btn btn-large btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/transactions/stats.html.erb
<% provide(:title, 'Statistics') %>
<div class="row">
	<aside class="span4">
	    <section>
	    </section>
	</aside>
	<div class="span8 center">
		<h3>Transactions Statistics</h3>

		<div class="transaction-box">
			<%= high_chart("my_id_income", @chart_income) do |c| %>
	          <%= raw "options.tooltip.formatter = function() {return '<b>'+ this.point.name +'</b>: '+ this.y;}"  %>
	          <%= raw "options.plotOptions.pie.dataLabels.formatter = function() { if (this.y > 5) return this.point.name + ': AU$'+this.y; }"  %>
      		<% end %>
      	</div>
      			<div class="transaction-box">
			<%= high_chart("my_id_income_percentage", @chart_income_percentage) do |c| %>
	          <%= raw "options.tooltip.formatter = function() {return '<b>'+ this.point.name +'</b>: '+ this.y +' %';}"  %>
	          <%= raw "options.plotOptions.pie.dataLabels.formatter = function() { if (this.y > 5) return this.point.name + ': '+this.y +'%'; }"  %>
      		<% end %>
      	</div>
      	<div class="transaction-box">
      		<%= high_chart("my_id_expense", @chart_expense) do |c| %>
	          <%= raw "options.tooltip.formatter = function() {return '<b>'+ this.point.name +'</b>: '+ this.y;}"  %>
	          <%= raw "options.plotOptions.pie.dataLabels.formatter = function() { if (this.y > 5) return this.point.name + ': AU$'+this.y; }"  %>
      		<% end %>
		</div>
      	<div class="transaction-box">
      		<%= high_chart("my_id_expense_percentage", @chart_expense_percentage) do |c| %>
	          <%= raw "options.tooltip.formatter = function() {return '<b>'+ this.point.name +'</b>: '+ this.y +' %';}"  %>
	          <%= raw "options.plotOptions.pie.dataLabels.formatter = function() { if (this.y > 5) return this.point.name + ': '+this.y +'%'; }"  %>
      		<% end %>
		</div>

  	</div>
 </div>