config/routes.rb
RomaMoneyRails::Application.routes.draw do
   #get "transactions/new"
  # get "transactions/create"
  # get "transactions/edit"
  # get "transactions/update"
  # get "transactions/destroy"
  
  # get "accounts/new"
  # get "accounts/destroy"
  #get "users/new"
  root :to => "home#index"


  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

 # root  'home#index'
  match '/',        to: 'home#index',    via: 'get'
  match '/home',    to: 'home#index',    via: 'get'
  match '/help',    to: 'home#help',    via: 'get'
#  match '/about',   to: 'static_pages#about',   via: 'get'
#  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/createAccount',  to: 'accounts#new',            via: 'get'
  match '/createTransaction',  to: 'transactions#new',            via: 'get'

  match '/stats',  to: 'transactions#stats',            via: 'get'

  match '/invite_user_to_account',  to: 'accounts#invite_user_to_account',            via: 'post'


  resources :accounts do
    member do
        post :invite_user_to_account
    end
  end


  resources :transactions do
    member do
      get :stats
    end
  end
    
  resources :users do
    member do
      get :change_to_this, :change_account, :change_account_ajax   #define following_user_path, followers_user_path
    end
  end

    #member do
    #  get :xxx, :yyy   #define xxx_user_path, yyy_user_path
  #  end
  
 resources :sessions, only: [:new, :create, :destroy]


end

app/views/layouts/_copywrite.html.erb
<%if false%>
<!--<script type="text/javascript">
  $('document').ready(function() {
  $("#sendToTopPage").click(function(){
    $(window).scrollTop(0);
   });
});
</script>
-->
<%end%>
<div id="copywrite">
  <div class="content" >
      <small>
        <p id="pCopywrite">
          2013 Anderson Araújo Lopes(RomaLopes) 
          <a href="http://www.linkedin.com/profile/view?id=50401015" title="Connect with me on linkedIn" target="_blank">
            <i class="fa btn-mini fa-linkedin"></i>Linkedin</a>
          <a href="http://twitter.com/romalopes" title="Follow me on twitter" target="_blank">
            <i class="fa btn-mini fa-twitter"></i>Twitter</a>
          <a href="http://facebook.com/romalopes" title="Follow me on facebook" target="_blank">
            <i class="fa btn-mini fa-facebook"></i>Facebook</a>
          <a href="http://github.com/romalopes/romaMoneyRails" title="Access project on Github" target="_blank">
            <i class="fa btn-mini fa-github"></i>Github</a>
          
          <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" src="http://platform.twitter.com/widgets/tweet_button.1384205748.html#_=1384487896697&amp;count=horizontal&amp;id=twitter-widget-0&amp;lang=en&amp;original_referer=http%3A%2F%2Fnoizwaves.github.io%2Fromalopes%2FromaMoneyRails%2F&amp;related=romalopes&amp;size=m&amp;text=Roma%20Money%20Rails&amp;url=http%3A%2F%2Fromalopes.blogspot.com&amp;via=romalopes" class="twitter-share-button twitter-tweet-button twitter-count-horizontal" title="Twitter Tweet Button" data-twttr-rendered="true" style="width: 100px; height: 20px;"></iframe>
          
          <iframe id="twitter-widget-1" scrolling="no" frameborder="0" allowtransparency="true" src="http://platform.twitter.com/widgets/follow_button.1384205748.html#_=1384487896706&amp;id=twitter-widget-1&amp;lang=en&amp;screen_name=romalopes&amp;show_count=false&amp;show_screen_name=true&amp;size=m" class="twitter-follow-button twitter-follow-button" title="Twitter Follow Button" data-twttr-rendered="true" style="width: 162px; height: 20px;"></iframe>
            

          <span id="sendToTopPage" class="pull-right">Go to Top <i class="icon-arrow-up icon-white"></i></span>
        </p>
      <small>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div id="footer">
    <div class="container">
      <div class="row">
        <div class="span3">
          <h3>Links</h3>
          <ul>
            <li><a href="/">Main project</a></li>
            <li><a target="_blank" href="http://github.com/romalopes/romaMoneyRails">Github</a></li>
            <li><a target="_blank" href="http://romalopes.blogspot.com">Blog</a></li>
          </ul>
        </div>
        <div class="span3">
          <h3>About me</h3>
          <ul>
            <li><a href="/">About Me</a></li>
          </ul>
        </div>
        <div class="span3">
          <h3>I'm social</h3>
          <ul>
            <li><a target="_blank" href="http://facebook.com/romalopes">Facebook</a></li>
            <li><a target="_blank" href="http://twitter.com/romalopes">Twitter</a></li>
            <li><a target="_blank" href="http://www.linkedin.com/profile/view?id=50401015">LinkedIn</a></li>
          </ul>
        </div>
        <div class="span3">
          <h3>Contact</h3>
          <ul>
            <li>Anderson Araújo Lopes</li>
            <li>(61)0402522058</li>
            <li>romalopes@yahoo.com.br</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%# navigation styled for Twitter Bootstrap 2.3 %>
<% if false%>
<!--
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <div class="navbar navbar-fixed-top">
          <nav class="navbar-inner">
            <ul class="nav">
              <li><%= link_to 'Home', root_path %><li>
              <%= render 'layouts/navigation_links' %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
-->
<%end%>
<%# navigation styled for Twitter Bootstrap 2.3 %>
<header class="navbar navbar-fixed-top navbar-inverse" >
  <div class="navbar-inner" style="padding:0px">
    <div class="container" style="padding:0 0 5px 5px">
      <%= link_to image_tag("home.png", alt: "Roma Money Rails",:size => "30x30", :title => "Click here to return to Home"), root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-left">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Statistics", stats_transaction_path(current_user) %></li>
            <% if current_user.admin? %>
              <li><%= link_to "Users", users_path %></li>
            <%end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" style="background-color:#4B0082;" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <%else%>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
        <% if signed_in? %>
          <ul class="nav pull-right" style="padding:8px 5px 0px 5px">
            <li ><%= gravatar_for current_user, {size:30} %></li>
                <li> 
                  <small style="color:lightgray"><%= current_user.name %> </small>
                </li>
          </ul>
        <%end%>

      </nav>
    </div>
  </div>
</header> 

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 2.3 %>
<div id="messages">
	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) %>
	    <div class="alert-<%= name == :notice ? "success" : "error" %>">
	      <a class="close" data-dismiss="alert">&times;</a>
	      <%= content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"%>
	    </div>
	  <% end %>
	<% end %>
</div>
<!-- 
<%if false %>
	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) %>
	    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
	      <a class="close" data-dismiss="alert">&times;</a>
	      <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    </div>
	  <% end %>
	<% end %>

	<% flash.each do |name, msg| %>
	        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %>      
<%end%>

 -->

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<% if false%>
<!--    <title><%= content_for?(:title) ? yield(:title) : "Roma Money Rails" %></title> -->
<%end%>    
     <title><%= full_title_page(yield(:title)) %></title>

     <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Roma Money Rails" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
<!-- 
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
 -->
    <%= render 'layouts/shim' %>  <!-- Call the part with IE9-->
  </head>
  <body>
    <%# application layout styled for Twitter Bootstrap 2.3 %>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main role="main">
      <div class="content" style="padding-left:10px">
        <div class="row">
          <div class="span12">
            <div class="row">
              <div class="span4"></div>
              <div class="span8">
                <%= render 'layouts/messages' %> 
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="span12">
            <%= yield %>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <div class="span12">
              <%= debug(params) if Rails.env.development? %>
            </div>
          </div>
        </div>
      </div>

    </main>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/copywrite' %>
  </body>
</html>