config/routes.rb
RomaMoneyRails::Application.routes.draw do
   #get "transactions/new"
  # get "transactions/create"
  # get "transactions/edit"
  # get "transactions/update"
  # get "transactions/destroy"
  
  # get "accounts/new"
  # get "accounts/destroy"
  #get "users/new"
  root :to => "home#index"


  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

 # root  'home#index'
  match '/',        to: 'home#index',    via: 'get'
  match '/home',    to: 'home#index',    via: 'get'
  match '/help',    to: 'home#help',    via: 'get'
#  match '/about',   to: 'static_pages#about',   via: 'get'
#  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/createAccount',  to: 'accounts#new',            via: 'get'
  match '/createTransaction',  to: 'transactions#new',            via: 'get'

  match '/stats',  to: 'transactions#stats',            via: 'get'

  match '/invite_user_to_account',  to: 'accounts#invite_user_to_account',            via: 'post'


  resources :accounts do
    member do
        post :invite_user_to_account
    end
  end


  resources :transactions do
    member do
      get :stats
    end
  end
    
  resources :users do
    member do
      get :change_to_this, :change_account, :change_account_ajax   #define following_user_path, followers_user_path
    end
  end

    #member do
    #  get :xxx, :yyy   #define xxx_user_path, yyy_user_path
  #  end
  
 resources :sessions, only: [:new, :create, :destroy]


end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  has_many :user_accounts, dependent: :destroy
  has_many :users, through: :user_accounts

  has_many :transactions, dependent: :destroy
  
  validates :user_id, presence: true
  validates :name, presence: true, length: { minimum: 6, maximum: 50 }
  # before_create {self.balance = 0}
  
  def current_balance
    value = 0.0
    self.transactions.each {
      |t| 
      if t.is_income == true
        value += t.value  
      else
        value -= t.value  
      end
    }
    return value
  end

  def how_is_balance
    color = ""
    balance = current_balance
    if balance > 0
      color = "blue"
    else
      if balance < 0
        color = "red"
      end
    end
    return color
  end

  def user_manager?(user)
    if user.id == user_id
      return true
    end
    return false
  end

  def user_name
    if user_id == nil
      return ''
    end
    return User.find(user_id).name
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :signed_in_user

  def index
  	@accounts = current_user.accounts.paginate(page: params[:page])
  end
  def new
  	@account = Account.new
  end

  def create
    @account = current_user.accounts.build(account_params)

    oldAccount = current_user.accounts.find_by(name:@account.name)
    if oldAccount.present?
      flash[:error] = "Account #{@account.name} already exists."
      render 'new'
      return
    end

#DOUBT 
    Account.transaction do
      if @account.save
        flash[:success] = "Account #{@account.name} created!"
        redirect_to root_url
        if current_user.current_account == nil
          current_user.update_attribute(:current_account_id, @account.id)
        end

        user_account = UserAccount.new(user_id:current_user.id, account_id: @account.id)

        if !user_account.save
          flash[:error] = "User_Account not created."
          render 'new'
          return
        end
      else
        render 'new'
      end
    end
  end

  def edit
      @account = Account.find(params[:id])
    end

  def update
      @account = Account.find_by(id: params[:id])
      if @account == nil
        flash[:error] = "Account deleted by other user"
        redirect_to accounts_path
        return
      end

      if @account.update_attributes(account_params)
        # Handle a successful update.
        flash[:success] = "Account updated"
        redirect_to accounts_path
      else
        render 'edit'
      end
  end

  def destroy
      account = Account.find_by(id: params[:id])

      if account == nil
        flash[:error] = "Account deleted by other user"
        redirect_to accounts_path
        return
      end

      account_id = account.id

      #if he is the manager try search for all users that have this account
      #try to chante the current_account_id
      #destroy the account
      if account.user_manager?(current_user)
        account.destroy
        users = User.where("current_account_id = ?", account_id)
        users.each do |user|
            if user.current_account_id == account_id
              user.set_first_account_possible
            end
        end
      else
      #else only destroy the relationship
        #flash["user_account"] = "user_id: #{user_account.user_id}   account_id: #{user_account.account_id}"
        userAccount = UserAccount.find_by(user_id: current_user.id, account_id: account_id)
        userAccount.destroy
      end
      if current_user.current_account_id == account_id
        current_user.set_first_account_possible
      end

      #only destroy if 
      #countUserAccount = UserAccount.where("account_id = ?", account_id, false).count
      #if(countUserAccount == 1)
      #  account.destroy
      #end
      if current_user.current_account_id == nil
        redirect_to root_url
        return
      end
      flash[:success] = "Account deleted."
      redirect_to accounts_path
  end

  def invite_user_to_account
      user_id = params[:user_id]
      email = params[:email]
      account_id = params[:account_id]

      invited_user = User.find_by(email: email)
      if invited_user.nil?
          flash[:error] = "user #{email} not found"
      else
        if invited_user.id == user_id
          flash[:error] = "You are invinting yourself"
        else
          user_account = UserAccount.find_by(user_id: invited_user.id, account_id: account_id)
          if user_account.nil?
            user_account = UserAccount.new(user_id: invited_user.id, account_id: account_id)
            if user_account.save

              flash[:success] = "User invited"
              if invited_user.current_account_id == nil
                invited_user.update_attribute("current_account_id", account_id)
              end
            else
              flash[:error] = "Problem inviting user #{email}"
            end
          else
              flash[:error] = "Relationship already exists"
          end
        end
      end

      redirect_to accounts_path
  end

  private 
  	    def account_params
	      params.require(:account).permit(:name, :user_id, :description)
		end

end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/views/accounts/_account.html.erb
<li>
	<%=account.name%>
	<p><%=account.description%>
	<p class="value-<%=account.how_is_balance%>">
		<b>Balance:</b> $ <%= account.current_balance %>
	</p>
	<% if !account.user_manager?(current_user) %>
		<b>Owner:</b> <%= account.user_name %>
	<% else %>
		<b>You are the owner</b>
    <% end %>
	<p></p>
	<% if account.user_manager?(current_user) %>
		<%= link_to "Change", edit_account_path(account) %>
    	| <%= link_to "delete", account, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% else %>
    	<%= link_to "unassociate", account, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>

    <% if current_user.current_account == account %>
    	<span style="color:orange">| this is the current account</span>
    <%else%>
		| <%= link_to "change to this account", change_account_user_path(account) %>
	<%end%>
	<% if account.user_manager?(current_user) %>
<!-- 		<a hred="#" onclick="return showInviteUserToAccount()">Share this account</a>
 -->	| <button onclick="return showInviteUserToAccount(<%=account.id%>)" class="btn btn-small btn-primary">Share this account</button>
	
		<div id="inviteUserToAccount<%=account.id%>" style="display:none">
			<div class="span4 transaction-box">
				<%= form_tag(controller:"accounts", action:"invite_user_to_account", method:"post") do %>
					<%= label_tag(:email, "email:") %>
  					<%= text_field_tag(:email) %>
  					<%= hidden_field_tag(:user_id, current_user.id) %>
   					<%= hidden_field_tag(:account_id, account.id) %>
  					<center>
			    		<%= submit_tag "Add Transaction", class: "btn btn-large btn-primary" %>
	      			</center>
	    		<% end %>
			</div>
		</div>    	
	<%end%>
</li>

app/views/accounts/_fields_account.html.erb
 <%= render 'shared/error_messages', object: f.object %>


<%= f.hidden_field :user_id, :value => @current_user.id %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_area :description, size: "60x12", rows:3%>

<% if false %>
	<%= f.label "Force current Value" %>
	<%= f.text_field :balance %>
<% end %>

app/views/accounts/edit.html.erb
<% provide(:title, "Edit and Account") %>
<h1>Update an account</h1>
<div class="row">
  <aside class="span4">
      
  </aside>
  <div class="span6 offset3 transaction-box">
    <%= form_for(@account) do |f| %>
      <%= render 'fields_account', f: f %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/accounts/index.html.erb
<% provide(:title, 'All Accounts') %>
<div od="all_accounts" class="row">
  <aside class="span4">
      
  </aside>
  <div class="span8">
	<h3>All Accounts</h3>

	<%= will_paginate %>

	<ul class="accounts">
	  <% @accounts.each do |account| %>
	    <%= render account %>  <!-- Call view/accounts/_account.html.erb  -->
	  <% end %>
	</ul>  
	<%= will_paginate %>   
  </div>
</div>	

app/views/accounts/new.html.erb
<% provide(:title, 'Create Account') %>
<h1>Create a new Account</h1>
<div class="row">
  <aside class="span4">
      
  </aside>
  <div class="span6 offset3 transaction-box">
    <%= form_for(@account) do |f| %>

      <%= render 'fields_account', f: f %>
      <%= f.submit "Create a new account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>